### ISSUE TITLE
enable pry-bond by default

### ISSUE THREAD

**Issue by kaibioinfo** [pry/pry-bond#6]
I find it a bit strange that pry loads all plugins automatically, but you still have to manually enable them. If I don't want to use pry-bond, I would set pry-bond on a blacklist such that pry will not load it. The current situation is: starting pry with pry-bond installed will load pry-bond and all its dependencies but will not set pry-bond as default completer.

I would suggest to swap the current behaviour:

``` ruby
require "pry/bond" # set Pry::BondCompleter as default completer
require "pry/bond/unobtrusive" # load Pry::BondCompleter without setting it as default
```

This seems to be also more consistent to other pry plugins that enable themself automatically.

**Comment by ghost** [comment]
hey @kaibioinfo - generally speaking  i prefer unobtrusive by default and obtrusive through an explicit opt-in. you can use the `enable-bond!` command to opt-in inside a REPL session, and if you had a Gemfile you could say:

``` ruby
gem "pry-bond", require: ["pry-bond", "pry/bond/default"]
```

all in all though, i agree with you. i don't see `pry/bond/unobtrusive` as totally necessary, so we could drop that if you want. the completer interface in pry has changed a little, to better support concurrent environments, a sample: https://github.com/pry/pry/commit/193a229b66f96cd85414010e6c0b516528664628

i think pry-bond would need updated as well. if you're interested please send a PR, or in time i can get around to it :) your suggestion in this issue is good, feel free to go ahead with it as well, or i will also get around to it in time :)

**Comment by kaibioinfo** [comment]
Hi,

On 03.04.2014 17:30, Robert wrote:

> the completer interface in pry has changed a little, to better support 
> concurrent environments, a sample: pry/pry@193a229 
> https://github.com/pry/pry/commit/193a229b66f96cd85414010e6c0b516528664628
> 
> i think pry-bond would need updated as well.

in fact I'm working the last few hours on that. Unfortunately, there 
seems to be no easy way to make Bond fit for concurrent environments (my 
current solution is adding a Mutex and let the completion be 
synchronized).  At the moment I have the following problems:
- while Bond::Agent can be used simultaneous in different threads, the 
  mission objects that do the completion share a global binding variable
- pry uses completion_procs from coolline or readline. For bond you need 
  the complete line as input, but currently pry just gives the last word 
  to the Pry#complete call. You would have to change this behaviour in 
  some setup of pry/bond, but then you have "platform-dependent" 
  (Coolline, Readline, some Jruby readline stuff?) code everywhere. It 
  would be nicer if pry would give Pry#complete the last word as well as 
  the last input line

The second issue could be solved very easily. But the first issue cannot 
be solved unless you rewrite Bond. As Bond seems to be still an project 
under active development I could fork it and make a push request for 
Bond lib without "global states"

best regards,
Kai

**Comment by ghost** [comment]
@kaibioinfo that's extremely good to know. we should tackle those problems without a doubt, but for now one of the most useful steps would be to localize an instance of `Pry` to `Pry::BondCompleter`, to get us one step closer to something that doesn't need a global reference(`Pry.current`) to implement itself.

if pry can make this situation better then let's talk about that too, but maybe the smallest step for now will get us somewhere.
